services:

  db:
    image: postgres:latest
    expose:
      - "5432"
    env_file:
      - .env.docker
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    entrypoint: ./docker/server/server-entrypoint.sh
    expose:
      - "8000"
    env_file:
      - .env.docker
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server

volumes:
  postgres_data:
  data: